<?php

namespace EllevenFw\Test\Core\Controller\Types;

use EllevenFw\Core\Controller\Types\ControllerBase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:47:35.
 */
class ControllerBaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ControllerBase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ControllerBase();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
