<?php

namespace EllevenFw\Test\Core\Exception\Types;

use EllevenFw\Core\Exception\Types\RoutingException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:49:06.
 */
class RoutingExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RoutingException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RoutingException();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
