<?php

namespace EllevenFw\Test\Core\View;

use EllevenFw\Core\View\Partial;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:47:55.
 */
class PartialTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Partial
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Partial();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
