<?php

namespace EllevenFw\Test\Core\View;

use EllevenFw\Core\View\View;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:48:17.
 */
class ViewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new View();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
