<?php

namespace EllevenFw\Core\Exception\Types;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:48:48.
 */
class CoreExceptionTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var CoreException
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CoreException;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

}
