<?php

namespace EllevenFw\Test\Utility\Api;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:45:52.
 */
class GenerateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Generate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Generate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
