<?php

namespace EllevenFw\Test\Utility\Project;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:45:40.
 */
class ReverseEngineeringTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ReverseEngineering
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ReverseEngineering;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
