<?php

namespace EllevenFw\Utility\Database;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:45:33.
 */
class DumpTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var Dump
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Dump;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

}
