<?php

namespace EllevenFw\Test\Core\Environment\Types;

use EllevenFw\Core\Environment\Types\TestEnvironment;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 22:48:42.
 */
class TestEnvironmentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TestEnvironment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TestEnvironment();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
