<?php

namespace EllevenFw\Test\Core\View\Types;

use EllevenFw\Core\View\Types\JsonView;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-24 at 23:03:04.
 */
class JsonViewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var JsonView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JsonView();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EllevenFw\Core\View\Types\JsonView::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
